Repository trace4cats/trace4cats-cloudtrace, pull requests merged in 2021-07, with the labels that each got.

#9 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#10 Update trace4cats-exporter-http to 0.12.0-RC1+162-70070fb2
  project/Dependencies.scala
Labels: dependency-update

#11 Update java-jwt to 3.18.0
  project/Dependencies.scala
Labels: dependency-update

#8 Update trace4cats-exporter-common, ... to 0.12.0-RC1+191-347e4fc7
  build.sbt
  project/Dependencies.scala
Labels: dependency-update

#16 Update java-jwt to 3.18.1
  project/Dependencies.scala
Labels: dependency-update

#17 Update google-cloud-trace to 1.4.2
  project/Dependencies.scala
Labels: dependency-update

#18 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#19 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#20 Update scala-collection-compat to 2.5.0
  project/Dependencies.scala
Labels: dependency-update

#21 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#22 Update google-auth-library-credentials to 0.27.0
  project/Dependencies.scala
Labels: dependency-update

#24 Update google-auth-library-credentials to 1.0.0
  project/Dependencies.scala
Labels: dependency-update

#25 Delay `GoogleAccountParser` properly
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/GoogleAccountParser.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/OAuthTokenProvider.scala
Labels: enhancement, ready-to-merge, skip-release

#23 Add Scala 3
  .github/mergify.yml
  .github/workflows/ci.yml
  ci-release.sbt
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/StackdriverHttpSpanExporter.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/AccessToken.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/CachedTokenProvider.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/GoogleAccountParser.scala
  modules/stackdriver-http-exporter/src/main/scala/io/janstenpickle/trace4cats/stackdriver/oauth/package.scala
  modules/stackdriver-http-exporter/src/test/scala/io/janstenpickle/trace4cats/stackdriver/oauth/CachedTokenProviderSpec.scala
  project/Dependencies.scala
Labels: enhancement
